-- ============================================================
-- JAM PORTAL — quién puede entrar
-- ------------------------------------------------------------
-- Esto es una PLANTILLA. La lista de verdad vive solo en la base,
-- no acá: son mails de personas y este repo es público.
--
-- Para sumar a alguien, desde el SQL Editor de Supabase (o por
-- psql), con su mail de verdad:
--
--     insert into miembro (email) values ('quien@sea.com')
--     on conflict (email) do nothing;
--
-- Para sacar a alguien:
--
--     delete from miembro where email = 'quien@sea.com';
--
-- Sacarlo de la lista lo deja afuera en el acto: la sesión le
-- sigue existiendo pero la base deja de devolverle filas.
--
-- Para ver quiénes están:
--
--     select email, alta::date from miembro order by alta;
-- ============================================================

-- Sin filas a propósito. Cargalos a mano con el insert de arriba.
